#!/usr/bin/env node

'use strict';

const fs = require('fs');
const path = require('path');
const { loadAgent } = require('./parse-agent');

const MODEL_MAP = Object.freeze({
  opus: 'gpt-5.4',
  sonnet: 'gpt-5.4-mini',
  haiku: 'gpt-5.4-mini',
});

const EFFORT_MAP = Object.freeze({
  high: 'high',
  medium: 'medium',
  low: 'low',
});

function resolveModelMapping(parsedAgent, options = {}) {
  const configuredMap = options.modelMapping && typeof options.modelMapping === 'object'
    ? options.modelMapping
    : {};
  const sourceModel = parsedAgent.frontmatter.model || 'opus';
  const configured = configuredMap[sourceModel];
  const fallback = MODEL_MAP[sourceModel];
  if (configured) {
    return {
      sourceModel,
      mappedModel: configured,
      mappingSource: 'config',
      warning: null,
    };
  }
  if (fallback) {
    return {
      sourceModel,
      mappedModel: fallback,
      mappingSource: 'default',
      warning: null,
    };
  }
  return {
    sourceModel,
    mappedModel: 'gpt-5.4',
    mappingSource: 'fallback',
    warning: `No model mapping found for "${sourceModel}". Falling back to gpt-5.4.`,
  };
}

function escapeTomlMultiline(value) {
  return value.replace(/"""/g, '\\"""');
}

function formatTomlStringArray(values) {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`;
}

function renderCodexToml(parsedAgent, options = {}) {
  const modelResolution = resolveModelMapping(parsedAgent, options);
  const effort = EFFORT_MAP[parsedAgent.frontmatter.effort] || 'high';
  const description = (parsedAgent.frontmatter.description || '').replace(/"/g, '\\"');
  const instructions = escapeTomlMultiline(parsedAgent.body);
  const warnings = [];

  if (modelResolution.warning) warnings.push(modelResolution.warning);
  if (parsedAgent.body.length > 4000) {
    warnings.push('Instructions exceed legacy 4000-character projection limit. Full instructions are preserved.');
  }

  return [
    '# Generated by Citadel. Do not edit manually.',
    `# Source: agents/${parsedAgent.frontmatter.name || parsedAgent.name}.md`,
    '',
    `name = "${parsedAgent.frontmatter.name || parsedAgent.name}"`,
    `description = "${description}"`,
    `model = "${modelResolution.mappedModel}"`,
    `model_reasoning_effort = "${effort}"`,
    '',
    '[citadel_projection]',
    'schema_version = 1',
    `source = "agents/${parsedAgent.frontmatter.name || parsedAgent.name}.md"`,
    `source_model = "${modelResolution.sourceModel}"`,
    `mapped_model = "${modelResolution.mappedModel}"`,
    `model_mapping_source = "${modelResolution.mappingSource}"`,
    `instruction_chars = ${parsedAgent.body.length}`,
    'instruction_fidelity = "full"',
    `warnings = ${formatTomlStringArray(warnings)}`,
    '',
    'developer_instructions = """',
    instructions,
    '"""',
    '',
  ].join('\n');
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function projectAgentToCodex(agentPath, targetBaseDir, options = {}) {
  const parsedAgent = loadAgent(agentPath);
  const targetPath = path.join(targetBaseDir, `${parsedAgent.frontmatter.name || parsedAgent.name}.toml`);
  const toml = renderCodexToml(parsedAgent, options);

  if (!options.dryRun) {
    ensureDir(path.dirname(targetPath));
    fs.writeFileSync(targetPath, toml, 'utf8');
  }

  return {
    parsedAgent,
    projection: {
      sourceAgent: `${parsedAgent.frontmatter.name || parsedAgent.name}.md`,
      instructionChars: parsedAgent.body.length,
    },
    output: {
      tomlPath: targetPath,
      toml,
    },
  };
}

module.exports = Object.freeze({
  resolveModelMapping,
  renderCodexToml,
  projectAgentToCodex,
});
